# Simple Chat plugin created by Louis_292
# This is the config file

# Edit the Chat Format you can use: {PLAYER_NAME} {MESSAGE} {PLAYER_DISPLAY_NAME}
chat_format: "{PLAYER_NAME}: {MESSAGE}"

# silent console, do not show the message in console
silent_console: false

# play sound on message
play_sound: true

# allow color chat
color_chat:
  require_permission: false
  permission: "chat.color"